server:
  port: 8761
 
eureka:
  instance:
    hostname: eurekaserver2
    appname: eureka-cluster
  environment: local
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8762/eureka/
    registerWithEureka: true
    fetchRegistry: true

    
    